const seedRecipes = [
  { id: 1, title: 'Romige pasta met tomaat', emoji: '🍝', color: 'peach', category: 'Pasta', time: '25 min', servings: 2, favorite: true, description: 'Een snelle, romige pasta voor doordeweeks.', ingredients: [{ name: 'Olijfolie', quantity: 100, unit: 'ml' }, { name: 'Pasta', quantity: 300, unit: 'g' }, { name: 'Tomaten', quantity: 2, unit: 'stuks' }, { name: 'Parmezaanse kaas', quantity: 50, unit: 'g' }], steps: ['Breng ruim water met een snuf zout aan de kook.', 'Kook de pasta beetgaar volgens de verpakking.', 'Bak de tomaten kort in de olijfolie en meng met de pasta.', 'Werk af met Parmezaanse kaas.'] },
  { id: 2, title: 'Citroen risotto', emoji: '🍋', color: 'yellow', category: 'Eenpansgerecht', time: '40 min', servings: 4, favorite: false, description: 'Zacht, fris en precies goed voor een gezellige avond.', ingredients: [{ name: 'Risottorijst', quantity: 300, unit: 'g' }, { name: 'Citroen', quantity: 1, unit: 'stuk' }, { name: 'Boter', quantity: 40, unit: 'g' }, { name: 'Bouillon', quantity: 750, unit: 'ml' }], steps: ['Verwarm de bouillon in een pan.', 'Fruit de rijst glazig in boter.', 'Voeg beetje bij beetje bouillon toe en roer regelmatig.', 'Meng de citroenrasp erdoor en serveer warm.'] },
  { id: 3, title: 'Appeltaart van oma', emoji: '🍎', color: 'pink', category: 'Gebak', time: '1 u 25 min', servings: 8, favorite: true, description: 'Knapperig deeg, zachte appels en een vleugje kaneel.', ingredients: [{ name: 'Bloem', quantity: 300, unit: 'g' }, { name: 'Boter', quantity: 200, unit: 'g' }, { name: 'Suiker', quantity: 150, unit: 'g' }, { name: 'Appels', quantity: 4, unit: 'stuks' }], steps: ['Verwarm de oven voor op 180°C.', 'Meng bloem, boter en suiker tot een soepel deeg.', 'Bekleed de vorm en vul met appels.', 'Bak 50 minuten goudbruin.'] },
  { id: 4, title: 'Groene shakshuka', emoji: '🍳', color: 'green', category: 'Ontbijt', time: '20 min', servings: 2, favorite: false, description: 'Een kleurrijk ontbijt in één pan.', ingredients: [{ name: 'Eieren', quantity: 4, unit: 'stuks' }, { name: 'Spinazie', quantity: 200, unit: 'g' }, { name: 'Olijfolie', quantity: 15, unit: 'ml' }], steps: ['Bak de spinazie kort in olijfolie.', 'Maak kuiltjes en breek de eieren erin.', 'Laat met deksel garen tot het eiwit gestold is.'] }
];

const seedInventory = [
  { name: 'Olijfolie', quantity: 100, unit: 'ml', minimum: 200, icon: '🫒', group: 'Olie & sauzen' },
  { name: 'Bloem', quantity: 1.2, unit: 'kg', minimum: 0.5, icon: '🌾', group: 'Bakken' },
  { name: 'Boter', quantity: 250, unit: 'g', minimum: 100, icon: '🧈', group: 'Zuivel' },
  { name: 'Eieren', quantity: 6, unit: 'stuks', minimum: 6, icon: '🥚', group: 'Zuivel' },
  { name: 'Tomaten', quantity: 3, unit: 'stuks', minimum: 2, icon: '🍅', group: 'Groenten & fruit' },
  { name: 'Pasta', quantity: 500, unit: 'g', minimum: 250, icon: '🍝', group: 'Voorraadkast' }
];

const categories = [['🍰', 'Gebak'], ['🍝', 'Pasta'], ['🥘', 'Eenpans'], ['🍲', 'Soepen'], ['🍖', 'Vlees'], ['🐟', 'Vis'], ['🥗', 'Salades'], ['🥖', 'Brood'], ['🍳', 'Ontbijt'], ['🍮', 'Desserts'], ['🥫', 'Sauzen'], ['🥤', 'Dranken']];
let state = { page: 'home', recipes: structuredClone(seedRecipes), inventory: structuredClone(seedInventory), shopping: [], selected: [], activeRecipe: null, query: '', toast: '' };

const app = document.querySelector('#app');
const fmt = (n) => Number.isInteger(n) ? n : String(n).replace('.', ',');
const unitGrams = (q, u) => u === 'kg' ? q * 1000 : u === 'g' ? q : null;
function findStock(name, quantity, unit) {
  const item = state.inventory.find(i => i.name.toLowerCase() === name.toLowerCase());
  if (!item) return 0;
  const wanted = unitGrams(quantity, unit), available = unitGrams(item.quantity, item.unit);
  return wanted !== null && available !== null ? Math.min(available / wanted, 1) : item.unit === unit ? Math.min(item.quantity / quantity, 1) : 0;
}
function nav(page) { state.page = page; state.activeRecipe = null; render(); }
function shell(content) {
  return `<div class="layout"><aside class="sidebar"><a class="brand" onclick="go('home')"><span>🍳</span> mijn keuken</a><div class="sidebar-label">OVERZICHT</div>${sideLink('home','⌂','Home')}${sideLink('recipes','▤','Mijn recepten')}${sideLink('favorites','♡','Favorieten')}<div class="sidebar-label kitchen-label">MIJN KEUKEN</div>${sideLink('inventory','♧','Voorraad')}${sideLink('shopping','🛒','Boodschappenlijst')}${sideLink('make','✦','Wat kan ik maken?')}<div class="sidebar-bottom">${sideLink('settings','⚙','Instellingen')}<div class="profile"><span class="avatar">S</span><span><b>Sophie</b><small>Thuiskeuken</small></span><span>⌄</span></div></div></aside><main>${content}</main><nav class="mobile-nav">${sideLink('home','⌂','Home')}${sideLink('recipes','▤','Recepten')}${sideLink('inventory','♧','Voorraad')}${sideLink('shopping','🛒','Lijst')}<button onclick="go('add')"><b>＋</b><span>Toevoegen</span></button></nav></div>`;
}
function sideLink(page, icon, label) { return `<button class="nav-link ${state.page === page ? 'active' : ''}" onclick="go('${page}')"><i>${icon}</i><span>${label}</span></button>`; }
function recipeCard(r, selectable = false) { const checked = state.selected.includes(r.id); return `<article class="recipe-card ${selectable ? 'selectable' : ''}" onclick="${selectable ? `toggleSelect(${r.id})` : `openRecipe(${r.id})`}"><div class="food-art ${r.color}"><span>${r.emoji}</span>${selectable ? `<b class="select-box ${checked ? 'checked':''}">${checked ? '✓' : ''}</b>` : ''}<button class="heart ${r.favorite ? 'liked' : ''}" onclick="event.stopPropagation();toggleFavorite(${r.id})">${r.favorite ? '♥' : '♡'}</button></div><div class="recipe-copy"><p>${r.category} <span>·</span> ${r.time}</p><h3>${r.title}</h3><small>👥 ${r.servings} personen</small></div></article>`; }
function home() { return shell(`<header class="top"><div><p class="eyebrow">GOEDEMORGEN, SOPHIE</p><h1>Wat eten we vandaag?</h1></div><div class="top-actions"><button class="icon-button">⌕</button><button class="notification">♧<b></b></button><button class="add-button" onclick="go('add')">＋ <span>Recept toevoegen</span></button></div></header><section class="search-wrap"><span>⌕</span><input placeholder="Zoek in mijn recepten..." value="${state.query}" oninput="searchHome(this.value)"/><kbd>⌘ K</kbd></section><section class="section-heading"><div><h2>Mijn recepten</h2><p>Een beetje inspiratie voor elke dag.</p></div><button class="text-button" onclick="go('recipes')">Bekijk alles <b>→</b></button></section><section class="categories">${categories.map(([e,n]) => `<button onclick="filterCategory('${n}')"><span>${e}</span>${n}</button>`).join('')}</section><section class="section-heading today"><div><h2>Wat wil je vandaag maken?</h2><p>Gekozen op basis van jouw favorieten en voorraad.</p></div><div class="arrows"><button>←</button><button>→</button></div></section><section class="card-grid featured">${state.recipes.filter(r => !state.query || (r.title+r.category).toLowerCase().includes(state.query.toLowerCase())).slice(0,3).map(r => recipeCard(r)).join('') || '<p>Geen recepten gevonden.</p>'}</section><section class="insights"><article class="list-summary"><div class="summary-icon coral">🛒</div><div><p>BOODSCHAPPENLIJST</p><h3>${state.shopping.length || 7} producten nodig</h3><small>${state.shopping.length ? 'Klaar om af te vinken' : 'Voor jouw geplande recepten'}</small></div><button onclick="go('shopping')">Bekijk lijst <b>→</b></button></article><article class="list-summary"><div class="summary-icon yellow-icon">♧</div><div><p>MIJN VOORRAAD</p><h3>${state.inventory.length} ingrediënten beschikbaar</h3><small>${state.inventory.filter(i=>i.quantity<=i.minimum).length} bijna op</small></div><button onclick="go('inventory')">Bekijk voorraad <b>→</b></button></article></section>`); }
function recipesPage() { return shell(`<header class="page-header"><div><p class="eyebrow">JOUW COLLECTIE</p><h1>Mijn recepten</h1><p>${state.recipes.length} recepten om van te genieten.</p></div><button class="add-button" onclick="go('add')">＋ Recept toevoegen</button></header><section class="toolbar"><div class="search-wrap compact"><span>⌕</span><input placeholder="Zoek op naam, ingrediënt of tag..." oninput="filterRecipes(this.value)"/></div><button class="filter">☷ Filters</button></section><section class="card-grid all-recipes">${state.recipes.map(r=>recipeCard(r,true)).join('')}</section>${state.selected.length ? `<div class="selection-bar"><span><b>${state.selected.length}</b> recepten geselecteerd</span><button onclick="createCombinedList()">🛒 Maak gecombineerde lijst</button></div>` : ''}`); }
function inventoryPage() { return shell(`<header class="page-header"><div><p class="eyebrow">MIJN KEUKEN</p><h1>Mijn voorraad</h1><p>Houd bij wat je in huis hebt.</p></div><button class="add-button" onclick="addInventory()">＋ Voorraad toevoegen</button></header><section class="stock-alert"><span>⚠</span><div><b>${state.inventory.filter(i=>i.quantity<=i.minimum).length} producten zijn bijna op</b><p>Voeg ze met één tik toe aan je boodschappenlijst.</p></div><button onclick="addLowStock()">Toevoegen aan lijst</button></section><section class="inventory-grid">${state.inventory.map(i=>`<article class="inventory-item"><span>${i.icon}</span><div><h3>${i.name}</h3><p>${i.group}</p></div><b>${fmt(i.quantity)} ${i.unit}</b><button onclick="adjustStock('${i.name}',-1)">−</button><button onclick="adjustStock('${i.name}',1)">＋</button><small class="${i.quantity<=i.minimum?'low':''}">${i.quantity<=i.minimum?'Bijna op · minimum '+fmt(i.minimum)+' '+i.unit:'Op voorraad'}</small></article>`).join('')}</section>`); }
function shoppingPage() { return shell(`<header class="page-header"><div><p class="eyebrow">KLAAR VOOR DE WINKEL</p><h1>Boodschappenlijst</h1><p>${state.shopping.length ? `${state.shopping.length} producten op je lijst.` : 'Nog niets nodig — wat fijn!'}</p></div><button class="outline-button" onclick="clearShopping()">Lijst leegmaken</button></header>${state.shopping.length ? `<section class="shopping-list">${state.shopping.map((item,i)=>`<label class="shopping-item ${item.checked?'done':''}"><input type="checkbox" ${item.checked?'checked':''} onchange="checkItem(${i})"/><span class="checkmark">✓</span><span class="item-icon">${iconFor(item.name)}</span><b>${item.name}</b><span>${fmt(item.quantity)} ${item.unit}</span></label>`).join('')}</section>` : `<section class="empty"><span>🧺</span><h2>Je lijst is lekker leeg</h2><p>Selecteer recepten en wij berekenen precies wat je nog nodig hebt.</p><button class="add-button" onclick="go('recipes')">Recepten kiezen</button></section>`}`); }
function makePage() { const ranked = state.recipes.map(r => ({...r, pct: Math.round(r.ingredients.reduce((s,i)=>s+findStock(i.name,i.quantity,i.unit),0)/r.ingredients.length*100)})).sort((a,b)=>b.pct-a.pct); return shell(`<header class="page-header"><div><p class="eyebrow">SLIMME KEUKENASSISTENT</p><h1>Wat kan ik maken?</h1><p>Recepten afgestemd op wat er in je keuken ligt.</p></div></header><section class="availability-note"><span>✦</span><div><b>Jouw voorraad is geanalyseerd</b><p>We vergelijken elk ingrediënt met je actuele voorraad.</p></div></section><section class="availability-grid">${ranked.map(r=>`<article class="available-card"><div class="food-art ${r.color}"><span>${r.emoji}</span><em class="availability ${r.pct===100?'full':r.pct>60?'partial':'low-avail'}">${r.pct===100?'Alles in huis':r.pct+'% beschikbaar'}</em></div><h3>${r.title}</h3><p>${r.pct===100?'Je kunt direct beginnen.':`Nog ${r.ingredients.filter(i=>findStock(i.name,i.quantity,i.unit)<1).length} ingrediënten nodig.`}</p><button onclick="openRecipe(${r.id})">Bekijk recept →</button></article>`).join('')}</section>`); }
function addPage() { return shell(`<section class="add-page"><button class="back" onclick="go('home')">← Terug</button><div class="add-intro"><span>✦</span><p class="eyebrow">NIEUW RECEPT</p><h1>Hoe wil je beginnen?</h1><p>Kies een manier die voor jou werkt. We helpen je met de rest.</p></div><div class="add-options"><button class="add-option primary-option" onclick="showTextImport()"><span>📋</span><div><h3>Tekst of recept plakken</h3><p>Laat AI ingrediënten en stappen voor je herkennen.</p></div><b>→</b></button><button class="add-option" onclick="manualRecipe()"><span>✏️</span><div><h3>Zelf invoeren</h3><p>Begin met een leeg recept.</p></div><b>→</b></button><button class="add-option muted"><span>🔗</span><div><h3>Recept via link</h3><p>Binnenkort beschikbaar</p></div><small>BINNENKORT</small></button><button class="add-option muted"><span>📷</span><div><h3>Foto van recept</h3><p>Binnenkort beschikbaar</p></div><small>BINNENKORT</small></button></div></section>`); }
function detailPage(r) { const scale = state.servings || r.servings; return shell(`<header class="recipe-hero"><button class="back" onclick="go('recipes')">← Alle recepten</button><div class="recipe-title"><div class="hero-food ${r.color}">${r.emoji}</div><div><p>${r.category} · Zelf toegevoegd</p><h1>${r.title}</h1><p>${r.description}</p><button class="favorite-button ${r.favorite?'liked':''}" onclick="toggleFavorite(${r.id})">${r.favorite?'♥ Favoriet':'♡ Favoriet maken'}</button></div></div></header><section class="recipe-meta"><span>◷ <b>${r.time}</b><small>totale tijd</small></span><span>♨ <b>180°C</b><small>oven</small></span><span>♧ <b>${scale} personen</b><small><button onclick="changeServings(-1)">−</button> porties <button onclick="changeServings(1)">＋</button></small></span></section><section class="recipe-layout"><div><section class="ingredient-section"><div class="section-heading"><div><h2>Ingrediënten</h2><p>Voor ${scale} personen</p></div><button class="text-button" onclick="addMissing(${r.id})">🛒 Voeg ontbrekende toe</button></div>${r.ingredients.map(i=>{let q=i.quantity*scale/r.servings;let available=findStock(i.name,q,i.unit);return `<div class="ingredient-row"><span class="round-check"></span><b>${fmt(q)} ${i.unit}</b><span>${i.name}</span><small class="${available===1?'enough':'missing'}">${available===1?'In huis':'Niet genoeg'}</small></div>`}).join('')}<button class="use-stock" onclick="cookRecipe(${r.id})">🍳 Dit ga ik maken</button></section></div><section class="instructions"><h2>Bereiding</h2>${r.steps.map((s,i)=>`<article><b>${i+1}</b><p>${s}</p></article>`).join('')}</section></section>`); }
function render() { let body = state.page==='home'?home():state.page==='recipes'||state.page==='favorites'?recipesPage():state.page==='inventory'?inventoryPage():state.page==='shopping'?shoppingPage():state.page==='make'?makePage():state.page==='add'?addPage():state.page==='detail'?detailPage(state.activeRecipe):home(); app.innerHTML = body + (state.toast?`<div class="toast">✓ ${state.toast}</div>`:''); }
window.go=nav; window.openRecipe=(id)=>{state.activeRecipe=state.recipes.find(r=>r.id===id);state.servings=state.activeRecipe.servings;state.page='detail';render()}; window.toggleFavorite=(id)=>{let r=state.recipes.find(x=>x.id===id);r.favorite=!r.favorite;render()}; window.toggleSelect=(id)=>{state.selected=state.selected.includes(id)?state.selected.filter(x=>x!==id):[...state.selected,id];render()}; window.searchHome=(q)=>{state.query=q;render()}; window.filterCategory=(c)=>{state.page='recipes';render();setTimeout(()=>document.querySelector('.compact input').value=c,0)}; window.filterRecipes=(q)=>{document.querySelector('.all-recipes').innerHTML=state.recipes.filter(r=>(r.title+r.category+r.ingredients.map(i=>i.name).join(' ')).toLowerCase().includes(q.toLowerCase())).map(r=>recipeCard(r,true)).join('')||'<p>Geen recepten gevonden.</p>'};
window.changeServings=(n)=>{state.servings=Math.max(1,state.servings+n);render()}; window.adjustStock=(name,n)=>{let i=state.inventory.find(x=>x.name===name);i.quantity=Math.max(0,i.quantity+n*(i.unit==='kg'?0.1:1));render()}; window.addInventory=()=>{let n=prompt('Welk ingrediënt wil je toevoegen?');if(n){state.inventory.push({name:n,quantity:1,unit:'stuks',minimum:0,icon:'🥫',group:'Voorraadkast'});state.toast=`${n} is toegevoegd aan je voorraad`;render()}};
function convert(q,u,target) { if (u===target) return q; if(u==='g'&&target==='kg')return q/1000;if(u==='kg'&&target==='g')return q*1000;return null; }
function addToShopping(name,q,unit) { const old=state.shopping.find(x=>x.name===name&&!x.checked); if(old){let cv=convert(q,unit,old.unit);if(cv!==null)old.quantity+=cv;else state.shopping.push({name,quantity:q,unit,checked:false});}else state.shopping.push({name,quantity:q,unit,checked:false}); }
function neededForRecipes(recipes) { const total=[]; recipes.forEach(r=>r.ingredients.forEach(i=>{let x=total.find(t=>t.name===i.name&&t.unit===i.unit);if(x)x.quantity+=i.quantity;else total.push({...i})})); return total; }
window.createCombinedList=()=>{neededForRecipes(state.recipes.filter(r=>state.selected.includes(r.id))).forEach(i=>{const stock=state.inventory.find(s=>s.name===i.name);let stockQ=stock?convert(stock.quantity,stock.unit,i.unit):0;if(stockQ===null)stockQ=0;let missing=Math.max(0,i.quantity-stockQ);if(missing)addToShopping(i.name,missing,i.unit)});state.toast='Je gecombineerde boodschappenlijst is klaar';state.selected=[];state.page='shopping';render()}; window.addMissing=(id)=>{let r=state.recipes.find(x=>x.id===id);r.ingredients.forEach(i=>{let stock=state.inventory.find(s=>s.name===i.name);let q=stock?convert(stock.quantity,stock.unit,i.unit):0;if(q===null)q=0;if(i.quantity>q)addToShopping(i.name,i.quantity-q,i.unit)});state.toast='Ontbrekende ingrediënten zijn toegevoegd';render()}; window.checkItem=(i)=>{state.shopping[i].checked=!state.shopping[i].checked;render()}; window.clearShopping=()=>{state.shopping=[];render()}; window.addLowStock=()=>{state.inventory.filter(i=>i.quantity<=i.minimum).forEach(i=>addToShopping(i.name,Math.max(0,i.minimum-i.quantity),i.unit));state.toast='Bijna-op producten toegevoegd';render()}; window.cookRecipe=(id)=>{let r=state.recipes.find(x=>x.id===id);if(confirm('Wil je de gebruikte ingrediënten van je voorraad aftrekken?')){r.ingredients.forEach(ing=>{let s=state.inventory.find(i=>i.name===ing.name);if(s){let used=convert(ing.quantity,s.unit,ing.unit);if(used!==null)s.quantity=Math.max(0,s.quantity-used)}});state.toast='Voorraad is bijgewerkt. Eet smakelijk!';render()}};
window.showTextImport=()=>{const text=prompt('Plak je recepttekst hier:', 'Pasta pesto\n200 g pasta\n50 ml extra vierge olijfolie\n2 tomaten');if(!text)return; const lines=text.split('\n').filter(Boolean);const title=lines[0].replace(/^#+/,'').trim()||'Nieuw recept';const ing=lines.slice(1).map(line=>{let m=line.match(/([\d.,]+)\s*(g|kg|ml|l|stuks?|eieren?)?\s+(.+)/i);if(!m)return null;let name=m[3].replace(/extra vierge olijfolie|olijfolie extra virgin/i,'Olijfolie').replace(/^tomaten?$/i,'Tomaten');return {name,quantity:parseFloat(m[1].replace(',','.')),unit:(m[2]||'stuks').replace(/^stuk$/,'stuks')};}).filter(Boolean);state.recipes.push({id:Date.now(),title,emoji:'🍲',color:'peach',category:'Zelf toegevoegd',time:'30 min',servings:4,favorite:false,description:'Geïmporteerd uit tekst — controleer de gegevens.',ingredients:ing,steps:['Volg de stappen uit het originele recept.']});state.toast='Recept herkend — controleer het gerust';state.page='recipes';render()}; window.manualRecipe=()=>{const title=prompt('Hoe heet je recept?','Mijn nieuwe recept');if(title){state.recipes.push({id:Date.now(),title,emoji:'🍽️',color:'yellow',category:'Eigen recept',time:'—',servings:4,favorite:false,description:'Mijn eigen recept.',ingredients:[],steps:['Voeg je bereidingsstappen toe.']});state.page='recipes';state.toast='Leeg recept aangemaakt';render()}}; window.iconFor=(n)=>({Olijfolie:'🫒',Bloem:'🌾',Boter:'🧈',Tomaten:'🍅',Pasta:'🍝'})[n]||'🛍️';
render();
